### ISSUE TITLE
Requesting fractional amounts of data gives unexpected results

### ISSUE THREAD

**Issue by jsteel44** [RSE-Cambridge/data-acc#77]
On a per-job burst buffer, requesting for example 2.8TB (or any fractional value) causes the per-job buffer not to be created and therefore not mounted for the running job.

On a persistent burst buffer, requesting for example 2.8TB (or any fractional value) always gives 1.4TB.

**Comment by JohnGarbutt** [comment]
This should be fixed in this commit: https://github.com/RSE-Cambridge/data-acc/commit/52038f217a4b18daa8bcd4a2260cf965cc8b434f

**Comment by jsteel44** [comment]
With v2-beta I've re-tested this and I find that both per-job and persistent buffers revert to 1.4TB when any fractional value is used. Eg "capacity=2.4TB" gives me 1.4TB.

**Comment by jsteel44** [comment]
I've re-tested this with v2.0-beta.4 and it is still an issue FYI.
